# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# @schema
# description: Blueprint properties
# type: object
# required: true
# @schema
blueprint:
  # @schema
  # description: Blueprints url
  # type: string
  # required: true
  # example: https://marketplace.krateo.io
  # @schema
  url: ""
  # @schema
  # description: Blueprints version
  # type: string
  # required: true
  # example: 0.0.1
  # @schema
  version: ""
  # @schema
  # description: Blueprints dedicated page (Composition)
  # type: boolean
  # default: true
  # @schema
  hasPage: false
  # @schema
  # description: Authentication configuration for private registries
  # type: object
  # @schema
  credentials:
    # @schema
    # description: Registry username
    # type: string
    # @schema
    username: ""
    # @schema
    # description: Reference to a secret containing the registry password or token
    # type: object
    # @schema
    passwordRef:
      # @schema
      # description: Secret key
      # type: string
      # required: true
      # @schema
      key: ""
      # @schema
      # description: Secret name
      # type: string
      # required: true
      # @schema
      name: ""
      # @schema
      # description: Secret namespace
      # type: string
      # required: true
      # @schema
      namespace: ""

# @schema
# description: Blueprint form properties 
# type: object
# @schema
form:
  # @schema
  # description: Blueprint form keys order 
  # type: boolean
  # default: false
  # @schema
  alphabeticalOrder: false
  # @schema
  # description: Blueprints dedicated page (Blueprint)
  # type: boolean
  # default: true
  # @schema
  hasPage: true
  # @schema
  # description: Blueprints form instructions
  # type: string
  # @schema
  instructions: ""

# @schema
# description: Blueprint panel properties 
# type: object
# required: true
# @schema
panel:
  # @schema
  # description: Blueprint panel title 
  # type: string
  # required: true
  # example: GitHub Scaffolding
  # @schema
  title: ""
  # @schema
  # description: Blueprint panel icon properties 
  # type: object
  # @schema
  icon:
    # @schema
    # description: Bleprint panel icon name 
    # type: string
    # example: fa-cubes
    # @schema
    name: ""
