# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# @schema
# description: Blueprint properties
# type: object
# required: true
# @schema
blueprint:
  # @schema
  # description: Blueprints repo
  # type: string
  # @schema
  repo: ""
  # @schema
  # description: Blueprints url
  # type: string
  # @schema
  url: https://marketplace.krateo.io
  # @schema
  # description: Blueprints version
  # type: string
  # required: true
  # @schema
  version: 0.0.1
  # @schema
  # description: Blueprints dedicated page (Composition)
  # type: boolean
  # required: true
  # default: true
  # @schema
  hasPage: false
  # @schema
  # description: Credentials for private blueprint registry
  # type: object
  # additionalProperties: false
  # @schema
  credentials:
    # @schema
    # description: Username for registry authentication
    # type: string
    # @schema
    username: ""
    # @schema
    # description: Reference to a secret containing the password
    # type: object
    # additionalProperties: false
    # @schema
    passwordRef:
      # @schema
      # description: Key in the secret
      # type: string
      # @schema
      key: ""
      # @schema
      # description: Name of the secret
      # type: string
      # @schema
      name: ""
      # @schema
      # description: Namespace of the secret
      # type: string
      # @schema
      namespace: ""

# @schema
# description: Blueprint form properties 
# type: object
# required: true
# @schema
form:
  # @schema
  # description: Blueprint form keys order 
  # type: boolean
  # required: true
  # default: false
  # @schema
  alphabeticalOrder: false

# @schema
# description: Blueprint panel properties 
# type: object
# required: true
# @schema
panel:
  # @schema
  # description: Blueprint panel title 
  # type: string
  # required: true
  # @schema
  title: GitHub Scaffolding
  # @schema
  # description: Blueprint panel icon properties 
  # type: object
  # @schema
  icon:
    # @schema
    # description: Bleprint panel icon name 
    # type: string
    # required: true
    # @schema
    name: fa-cubes

# @schema
# description: global properties section - if the Helm chart is installed via Composition Dynamic Controller, these are injected by default
# type: object
# additionalProperties: true
# @schema
global:
  # @schema
  # description: Composition Custom Resource metadata name
  # type: string
  # examples: [cloudnative-stack]
  # @schema    
  compositionName: cloudnative-stack