kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-panel-button-cleanup
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
    actions:
      rest:
        - id: cleanup
          resourceRefId: cleanup
          type: rest
          onSuccessNavigateTo: /blueprints
          successMessage: "Successfully deleted {{ .Release.Name }} blueprint in {{ .Release.Namespace }}"
  resourcesRefs:
    items:
      - id: cleanup
        apiVersion: templates.krateo.io/v1
        resource: restactions
        name: {{ .Release.Name }}-restaction-cleanup
        namespace: {{ .Release.Namespace }}
        verb: GET