apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    repo: {{ .Release.Name }}
    url: {{ .Values.blueprint.url }}
    version: {{ .Values.blueprint.version }}