kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-panel
  namespace: {{ .Release.Namespace }}
  labels:
    krateo.io/portal-page: blueprints
spec:
  apiRef:
    name: {{ .Release.Name }}-restaction-compositiondefinition-schema-ns
    namespace: {{ .Release.Namespace }}
  widgetData:
    allowedResources:
      - markdowns
      - buttons
      - forms
    clickActionId: blueprint-click-action
    footer:
      - resourceRefId: blueprint-panel-button
    tags:
      - {{ .Release.Namespace }}
      - {{ .Values.blueprint.version }}
    icon:
      name: {{ .Values.panel.icon.name }}
    items:
      - resourceRefId: blueprint-panel-markdown
    title: {{ .Values.panel.title }}
    actions:
      openDrawer:
        - id: blueprint-click-action
          resourceRefId: blueprint-form
          type: openDrawer
          size: large
          title: {{ .Values.panel.title }}
  widgetDataTemplate:
    - forPath: icon.color
      expression: ${ ((.getCompositionDefinition?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end) | first) // "grey" }
    - forPath: headerLeft
      expression: ${ ((.getCompositionDefinition?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "Ready:False" elif .status == "True" then "Ready:True" else "Ready:Unknown" end) | first) // "Ready:Unknown" }
    - forPath: headerRight
      expression: ${ .getCompositionDefinition // {} | .metadata.creationTimestamp // "In the process of being created" }
  resourcesRefs:
    items:
      - id: blueprint-panel-markdown
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Release.Name }}-panel-markdown
        namespace: {{ .Release.Namespace }}
        resource: markdowns
        verb: GET
      - id: blueprint-panel-button
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: {{ .Release.Name }}-panel-button-cleanup
        namespace: {{ .Release.Namespace }}
        resource: buttons
        verb: DELETE
      - id: blueprint-form
        apiVersion: widgets.templates.krateo.io/v1beta1
        {{- if eq .Values.form.alphabeticalOrder true }}
        name: {{ .Release.Name }}-form-alphabetical-order
        {{- else }}
        name: {{ .Release.Name }}-form-not-alphabetical-order
        {{- end }}
        namespace: {{ .Release.Namespace }}
        resource: forms
        verb: GET