kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-form-page-panel-form
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    items:
      - resourceRefId: blueprint-form
    title: {{ .Values.panel.title }}
  resourcesRefs:
    items:
      - id: blueprint-form
        apiVersion: widgets.templates.krateo.io/v1beta1
        {{- if eq .Values.form.alphabeticalOrder true }}
        name: {{ .Release.Name }}-form-alphabetical-order
        {{- else }}
        name: {{ .Release.Name }}-form-not-alphabetical-order
        {{- end }}
        namespace: {{ .Release.Namespace }}
        resource: forms
        verb: GET