{{- if eq .Values.form.hasPage true }}
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Route
metadata:
  name: {{ .Release.Name }}-form-page-route
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    path: /{{ .Release.Name }}-blueprint
    resourceRefId: form-page
  resourcesRefs:
    items:
      - id: form-page
        apiVersion: widgets.templates.krateo.io/v1beta1
        name: "{{ .Release.Name }}-form-page"
        namespace: {{ .Release.Namespace }}
        resource: pages
        verb: GET
{{- end }}