name: release-tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub App
        id: authenticate
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Extract latest Chart Version
        uses: tdemin/find-latest-tag@v1
        id: chart_version
        with:
          repo: https://${{ steps.authenticate.outputs.token }}@github.com/${{ github.repository }}.git

      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Version
        run: |
          echo CHART_VERSION:${{steps.chart_version.outputs.tag}}

      - name: Replace Version in Chart.yaml
        run: sed -i 's/CHART_VERSION/${{ steps.chart_version.outputs.tag }}/g' ./template/Chart.yaml

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ steps.authenticate.outputs.token }}
          charts_dir: ./
          charts_url: https://marketplace.krateo.io
          owner: krateoplatformops-blueprints
          repository: helm-charts
          branch: gh-pages
